export const words = [
    "el", "la", "un", "una", "los", "las", "unos", "unas", "y", "o", "pero",
    "porque", "aunque", "si", "entonces", "cuando", "donde", "quien", "cual",
    "como", "para", "sobre", "bajo", "ante", "con", "sin", "entre", "tras",
    "sin embargo", "por lo tanto", "además", "en cambio", "no obstante", "por consiguiente",
    "casa", "perro", "gato", "auto", "persona", "amigo", "día", "noche",
    "sol", "luna", "agua", "tierra", "fuego", "aire", "mar", "montaña",
    "camino", "puerta", "ventana", "música", "libro", "historia", "juego",
    "rojo", "azul", "verde", "amarillo", "negro", "blanco", "grande", "pequeño",
    "rápido", "lento", "nuevo", "viejo", "bonito", "feo", "alto", "bajo",
    "inteligente", "valiente", "perezoso", "honesto", "creativo", "paciente",
    "hablar", "habló", "hablará", "comer", "comió", "comerá", "correr", "corrió", "correrá",
    "saltar", "saltó", "saltará", "pensar", "pensó", "pensará", "vivir", "vivió", "vivirá",
    "mirar", "miró", "mirará", "escuchar", "escuchó", "escuchará", "dormir", "durmió", "dormirá",
    "soñar", "soñó", "soñará", "reír", "rió", "reirá", "llorar", "lloró", "llorará",
    "leer", "leyó", "leerá", "escribir", "escribió", "escribirá", "cantar", "cantó", "cantará",
    "bailar", "bailó", "bailará", "feliz", "triste", "fuerte", "débil", "caliente", "frío", "dulce", "amargo",
    "hoy", "ayer", "mañana", "siempre", "nunca", "a veces", "ahora", "después",
    "posiblemente", "seguramente", "afortunadamente", "desafortunadamente", "claramente",
    "quién", "qué", "cuándo", "dónde", "por qué", "cómo", "cuál", "cuánto",
    "primero", "segundo", "tercero", "último", "mejor", "peor", "igual", "diferente",
    "ciudad", "pueblo", "bosque", "río", "playa", "desierto", "invierno", "verano",
    "primavera", "otoño", "hombre", "mujer", "niño", "niña", "padre", "madre",
    "hermano", "hermana", "tío", "tía", "abuelo", "abuela", "primo", "prima",
    "mañana", "tarde", "noche", "temprano", "pronto", "nunca", "siempre",
    "difícil", "fácil", "interesante", "aburrido", "cansado", "emocionado", "enojado", "tranquilo",
    "hábito", "costumbre", "rutina", "actividad", "deporte", "trabajo", "oficio", "profesión",
    "universidad", "escuela", "clase", "materia", "examen", "tarea", "proyecto", "conocimiento",
    "sociedad", "cultura", "política", "economía", "ciencia", "tecnología", "historia", "arte",
    "felicidad", "justicia", "responsabilidad", "creatividad", "paciencia", "esperanza",
    "médico", "ingeniero", "profesor", "abogado", "arquitecto", "músico", "escritor", "actor",
    "trabajar", "trabajó", "trabajará", "descansar", "descansó", "descansará", "viajar", "viajó", "viajará",
    "explorar", "exploró", "explorará", "descubrir", "descubrió", "descubrirá", "aprender", "aprendió", "aprenderá",
    "enseñar", "enseñó", "enseñará", "practicar", "practicó", "practicará", "decidir", "decidió", "decidirá",
    "escoger", "escogió", "escogerá", "comprender", "comprendió", "comprenderá", "analizar", "analizó", "analizará",
    "crear", "creó", "creará", "construir", "construyó", "construirá", "destruir", "destruyó", "destruirá",
    "formar", "formó", "formará", "intentar", "intentó", "intentará", "lograr", "logró", "logrará",
    "fracasar", "fracasó", "fracasará", "mejorar", "mejoró", "mejorará", "empeorar", "empeoró", "empeorará",
    "olvidar", "olvidó", "olvidará", "recordar", "recordó", "recordará", "imaginar", "imaginó", "imaginará",
    "podría", "debería", "quisiera", "hubiera", "tendría", "habría", "sería",
    "yo", "tú", "él", "ella", "nosotros", "ustedes", "ellos",
    "confianza", "determinación", "ambición", "arrepentimiento", "melancolía", "optimismo", "paz",
    "esperanza", "duda", "miedo", "alegría", "tristeza", "sorpresa", "desconfianza", "amistad",
    "amor", "odio", "pasión", "indiferencia", "motivación", "inspiración", "desesperación", "calma"
  ];